### ISSUE TITLE
Upgraded to v3, getting: Error: Cannot find module 'gulp-hb'

### ISSUE THREAD

**Issue by spacedawwwg** [shannonmoeller/gulp-hb#30]
After upgrading to v3.0.0 I have now started getting

```
MacBook-Pro:project Paul$ gulp
module.js:339
    throw err;
    ^

Error: Cannot find module 'gulp-hb'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/ProjectPath/build/lab/lab--compile.js:5:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

I have tried removing `node_modules` and re-installing the whole lot, but I get the same issue.

I haven't changed a thing in my build scripts, so I am just wondering what has changed that might be causing the error?

NOTE: I use __require-dir__ to separate my gulp tasks

**Comment by spacedawwwg** [comment]
I have reverted back to v2.6.5 as that still works for now

**Comment by shannonmoeller** [comment]
Well that was embarrassing. I messed up the "main" field in the package.json. Fixed! Thanks.

Released as v3.0.1

**Comment by shannonmoeller** [comment]
Be sure to checkout the [changelog](https://github.com/shannonmoeller/gulp-hb/blob/master/CHANGELOG.md) as there are some known breaking changes. This just wasn't one of them.
